site_name: Fragment - Real-time audiovisual live coding platform
copyright: "<a href='https://www.fsynth.com'>© Julien Verneuil</a>"
pages:
- Fragment: 'index.md'
- Concept: 'concept.md'
- Getting started: 'getting_started.md'
- Documentation:
    - 'Sessions': 'tutorials/sessions.md'
    - 'User interface': 'ui.md'
    - 'GLSL': 'glsl.md'
    - 'Slices / Instruments': 'tutorials/instruments.md'
    - 'Synth / Audio server': 'tutorials/audio_server.md'
    - 'Session / Global Settings': 'settings.md'
    - 'Import dialog': 'tutorials/import.md'
    - 'Images import': 'tutorials/images_import.md'
    - 'Sounds import': 'tutorials/sounds_import.md'
    - 'Videos import': 'tutorials/videos_import.md'
    - 'Camera import': 'tutorials/camera_import.md'
    - 'Microphone import': 'tutorials/mic_import.md'
    - 'Desktop import': 'tutorials/dsk_import.md'
    - 'Canvas import': 'tutorials/canvas_import.md'
    - 'Processing.js import': 'tutorials/pjs_import.md'
    - 'Record dialog': 'tutorials/spectral_record.md'
    - 'MIDI': 'tutorials/midi.md'
    - 'OSC': 'tutorials/osc.md'
    - 'Graphics': 'tutorials/graphics.md'
    - 'Tools': 'tools.md'
- Tutorials (additive synthesis):
    - 'Fundamental': 'tutorials/fundamental.md'
    - 'Partials': 'tutorials/partials.md'
    - 'Waveforms': 'tutorials/waveforms.md'
    - 'Envelopes': 'tutorials/env.md'
    - 'Filters': 'tutorials/filters.md'
    - 'Multitimbrality': 'tutorials/multitimbrality.md'
    - 'Effects': 'tutorials/effects.md'
    - 'Feedback': 'tutorials/feedback.md'
    - 'Time axis': 'tutorials/time_axis.md'
- Credits: 'credits.md'
theme: readthedocs
site_favicon: "favicon.ico"
repo_url: "https://github.com/grz0zrg/fsynth"
repo_name: "github"
edit_uri: edit/master/documentation/mk/docs/
