site_name: Fragment - The Collaborative Spectral Synthesizer
copyright: "<a href='https://www.fsynth.com'>© Julien Verneuil</a>"
pages:
- Fragment: 'index.md'
- Concept: 'concept.md'
- Getting started: 'getting_started.md'
- Tutorials:
    - 'Sessions': 'tutorials/sessions.md'
    - 'User interface': 'ui.md'
    - 'GLSL': 'glsl.md'
    - 'Timbre': 'tutorials/timbre.md'
    - 'Slices': 'tutorials/slices.md'
    - 'Fundamental': 'tutorials/fundamental.md'
    - 'Partials': 'tutorials/partials.md'
    - 'Waveforms': 'tutorials/waveforms.md'
    - 'MIDI': 'tutorials/midi.md'
    - 'Envelopes': 'tutorials/env.md'
    - 'Filters': 'tutorials/filters.md'
    - 'Possibilities': 'tutorials/possibilities.md'
    - 'Effects': 'tutorials/effects.md'
    - 'Multitimbrality': 'tutorials/multitimbrality.md'
    - 'Synthesis': 'tutorials/synthesis_methods.md'
    - 'Feedback': 'tutorials/feedback.md'
    - 'Import dialog': 'tutorials/import.md'
    - 'Images import': 'tutorials/images_import.md'
    - 'Sounds import': 'tutorials/sounds_import.md'
    - 'Videos import': 'tutorials/videos_import.md'
    - 'Camera import': 'tutorials/camera_import.md'
    - 'Canvas import': 'tutorials/canvas_import.md'
    - 'Spectral recording': 'tutorials/spectral_record.md'
    - 'OSC': 'tutorials/osc.md'
    - 'Audio Server': 'tutorials/audio_server.md'
    - 'Visuals': 'tutorials/visuals.md'
- Settings: 'settings.md'
- Tips: 'tips.md'
- Tools: 'tools.md'
- Credits: 'credits.md'
theme: readthedocs
site_favicon: "favicon.ico"
repo_url: "https://github.com/grz0zrg/fsynth"
repo_name: "github"
edit_uri: edit/master/documentation/mk/docs/
